feature: syslog test can use toolsmith env
[#169068487](https://www.pivotaltracker.com/story/show/169068487)

Co-authored-by: Bruce Ricard <bricard@pivotal.io>

diff --git a/ci/tasks/syslog-test/task b/ci/tasks/syslog-test/task
--- a/ci/tasks/syslog-test/task
+++ b/ci/tasks/syslog-test/task
@@ -3,8 +3,15 @@ set -eu -o pipefail
 
 source routing-release-ci/ci/scripts/script_helpers.sh
 
-ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
-bosh_login "${ENVIRONMENT}"
+if [[ -d toolsmiths-metadata-dir ]]; then
+  ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
+  bosh_login "${ENVIRONMENT}"
+elif [[ -d deployments-routing ]]; then
+  bosh_login_toolsmtihs toolsmiths-metadata-dir
+else
+  echo "Failed to provide either \"toolsmiths-metadata-dir\" or \"deployments-routing\""
+  exit 1
+fi
 
 function cleanup() {
   pkill ssh || true
